# Web Standard Configuration File
name: JSONPlaceholder

api:
  base_token_url: https://jsonplaceholder.typicode.com
  base_url: https://jsonplaceholder.typicode.com

user:
  username: na
  password: na

database:
  host: qa-db.example.com
  port: 5432
  user: qa_user
  password: qa_password
  name: qa_db
  ssl: false