# Standard Configuration File
name: Shoftship Master Data Site
web:
  base_url: https://jaxvycswebqa.crowley.com
  browser: chrome

api:
  base_url: na

user:
  username: na
  password: na

database:
  host: na
  port: 5432
  user: qa_user
  password: qa_password
  name: qa_db
  ssl: false